### ISSUE TITLE
File name too long for plot image (OSError: [Errno 36] File name too long)

### ISSUE THREAD

**Issue by hdore** [anuradhawick/MetaBCC-LR#4]
Hello,

Thanks again for developing this tool. I am trying metaBCC-LR to bin metagenomic Nanopore reads from a natural community.
With default settings, I got 2360 bins on my dataset, which I think is way too much from what I know of this community (and what I see in the plots tends to confirm that it is overestimated), so I'm trying to tune the sensitivity.

I ran into an OS error while doing so, because of a file name too long when writing the image files
`OSError: [Errno 36] File name too long: 'metaBCCLR_default_params_output/images/Separation by composition Root-x-2-c-1-c-1-c-1-c-0-c-1-c-1-c-1-c-1-c-1-c-1-c-1-c-1-c-1-c-1-c-1-c-1-c-1-c-1-c-1-c-1-c-1-c-1-c-1-c-1-c-1-c-1-c-1-c-1-c-1-c-1-c-1-c-1-c-1-c-1-c-1-c-1-c-1-c-1-c-1-c-1-c-1-c-1-c-1-c-1-c-1-c-1-c-1-c-1-c-1-c-1-c-1-c-1-c-1-c-1-c-1.png`

I'm not sure to understand how these files are named? Is there a way to change that, or maybe to skip printing the file if there is an error?

Also, I think it would be interesting to know the estimated coverage for each bin (I guess that would be the mean or median coverage of the reads in the bin). Or maybe this is included in the misc/cluster-stats.txt file?

Thank you for your help,

Best regards

Hugo

**Comment by anuradhawick** [comment]
Hello, Thanks for reaching out.

The naming of these files comes from the way the clustering is done. We have the initial set `Root`. Then they are clustered using coverage then the resulting clusters are named as `R-x-1`, `R-x-2`, `R-x-3`, etc. Then the composition is used to cluster recursively.  `R-x-1-c-1`,  `R-x-1-c-2`,  `R-x-2-c-1`, etc. It is like a tree. The tool definitely overestimates the bins in your case. Could you try to lower the sensitivity parameter?

The OS error comes because our tool finds too many bins, which makes the file name too long for that particular bin's TSNE plot. **I will implement a way to turn of plotting in due course. Sorry for the inconvenience**.

```
--sensitivity SENSITIVITY, -s SENSITIVITY
                        Value between 1 and 10, Higher helps recovering low
                        abundant species (No. of species > 100)
```

**misc/cluster-stats.txt** contains the summaries for each bin and used internally to assign the rest of the reads to the bins identified. We do not estimate a single coverage value for reads, but rather compute a vector to represent the coverage of the species that the read might belong to. The explanation for the file is as follows.

```
Bin name
vector that represents the mean of coverage vectors in the bin
vector that represents the standard deviation of coverage vectors in the bin
vector that represents the mean of trimer composition vectors in the bin
vector that represents the standard deviation of trimer composition vectors in the bin
```
The above set of 5 lines repeat for each bin identified in **misc/cluster-stats.txt**.

Best regards
Anuradha

**Comment by hdore** [comment]
Hello Anuradha,

Thank you for your very detailed answers! It definitely helps.

Best regards,

Hugo
